### ISSUE TITLE
Can we do few-shot inference or one-shot inference?

### ISSUE THREAD

**Issue by ashutoshIITK** [ByungKwanLee/MoAI#14]
Is it possible to feed one image and caption and then do another inference as in few shot inference?

**Comment by ByungKwanLee** [comment]
Few shot inferneces should have ability to understand the multiple images (only texts can be possible). However, MoAI is not traoned with mutiple images and does not support multiple image tokens.

**Comment by ashutoshIITK** [comment]
Got it! Thank you for the quick response!
